### ISSUE TITLE
Signer crashing when invoking ListClosedChannels

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#193]
Attaching logs of signer panics, probably due to mismatched version. Currently running the breez sdk (from main branch) will crash for anyone with an old node.
We need a way to wait for the signer to upgrade. Knowing the upgrade has completed will allow us safely to schedule the node.

```
06-29 06:47:25.504  5972  5972 F DEBUG   : Abort message: 'called `Result::unwrap()` on an `Err` value: Unknown URI /cln.Node/ListClosedChannels, can't decode payload'
06-29 06:47:25.504  5972  5972 F DEBUG   :     x0  0000000000000000  x1  0000000000001732  x2  0000000000000006  x3  0000006f1fcc5f30
06-29 06:47:25.504  5972  5972 F DEBUG   :     x4  0000008080808080  x5  0000008080808080  x6  0000008080808080  x7  0000000000000020
06-29 06:47:25.504  5972  5972 F DEBUG   :     x8  00000000000000f0  x9  7523d5424e8e9d8c  x10 0000000000000000  x11 ffffffc0fffffbdf
06-29 06:47:25.504  5972  5972 F DEBUG   :     x12 0000000000000001  x13 6168436465736f6c  x14 0000007fcfc05fc8  x15 00000000fffffff2
06-29 06:47:25.504  5972  5972 F DEBUG   :     x16 00000072b6ffec80  x17 00000072b6fe0b70  x18 0000006f19b66000  x19 0000000000007401
06-29 06:47:25.504  5972  5972 F DEBUG   :     x20 0000000000001732  x21 00000000ffffffff  x22 0000006f3c3b0108  x23 0000006f1fcc6240
06-29 06:47:25.504  5972  5972 F DEBUG   :     x24 0000006f3bc42ea8  x25 0000000000000001  x26 0000006f3c43a000  x27 0000006f3b89f050
06-29 06:47:25.504  5972  5972 F DEBUG   :     x28 0000006f1fcc81b0  x29 0000006f1fcc5fb0
06-29 06:47:25.504  5972  5972 F DEBUG   :     lr  00000072b6f943e0  sp  0000006f1fcc5f10  pc  00000072b6f9440c  pst 0000000000000000
06-29 06:47:25.527  5972  5972 F DEBUG   : backtrace:
06-29 06:47:25.527  5972  5972 F DEBUG   :       #00 pc 000000000004e40c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 07fbaeed7b7a19203975f06be6f1d5ef)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #01 pc 0000000000bb4708  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (panic_abort::__rust_start_panic::abort::h3a74f1885f2f240b+4)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #02 pc 0000000000bb46fc  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (__rust_start_panic+8)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #03 pc 0000000000baa8e4  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (rust_panic+8)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #04 pc 0000000000baa768  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (std::panicking::rust_panic_with_hook::hae676ea4cb54d372+664)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #05 pc 0000000000baa4b0  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h28e3779ad5029fec+200)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #06 pc 0000000000ba9428  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (std::sys_common::backtrace::__rust_end_short_backtrace::hcc3186f99b814c53+4)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #07 pc 0000000000baa234  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (rust_begin_unwind+108)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #08 pc 0000000000bc5fb4  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (core::panicking::panic_fmt::hf634d2dad967350c+44)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #09 pc 0000000000bc62ec  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (core::result::unwrap_failed::heb325dbe9de0f88a+84)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #10 pc 00000000007f86ec  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (gl_client::signer::decode_request::hb0f3c5ae6b7804a4+300)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #11 pc 000000000065925c  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (_$LT$core..iter..adapters..map..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::try_fold::he72bdeb32a967cce+124)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #12 pc 000000000065b864  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (_$LT$core..iter..adapters..GenericShunt$LT$I$C$R$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::try_fold::h2c46d77e9eb25c7f+24)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #13 pc 000000000065b7b4  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (_$LT$core..iter..adapters..GenericShunt$LT$I$C$R$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h9de6188503659c3e+16)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #14 pc 000000000065fae0  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h350a73e924093d25+20)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #15 pc 0000000000678134  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (alloc::vec::in_place_collect::_$LT$impl$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$u20$for$u20$alloc..vec..Vec$LT$T$GT$$GT$::from_iter::h45fd8e120b10f24c+16)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #16 pc 0000000000673e28  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (core::iter::adapters::try_process::h200450a540816d6a+12)
06-29 06:47:25.527  5972  5972 F DEBUG   :       #17 pc 00000000006c80b8  /data/app/~~DPOdUO3DFkg1xW2uKwDkqw==/com.cBreez.client-0gKqvm9gmdWQUHN-YuImHg==/lib/arm64/libbreez_sdk_core.so (gl_client::signer::Signer::run_once::_$u7b$$u7b$closure$u7d$$u7d$::he49502e8fda515b2+7176)

```

**Comment by cdecker** [comment]
That looks a lot like a version mismatch indeed. The problem is that we can't decode an RPC call with a version that predactes the introduction of that RPC method into the library (rather unique incident which won't happen once we have full grpc coverage).

The solution here is threefold:

 - Make failing to decode the RPC call non-fatal, which may cause some signature requests to fail, but in this case we're failing on a read-only call, that only happened to be in the context due to a concurrent read-write call, which ended up at the signer
 - Filter out read-only calls on the node, since they should not influence the decision of whether a signature request is legitimate or not
 - Expose the `maybe_upgrade` scheduler RPC call in a way that the client can wait for it to complete before actually scheduling the node (this is a bit racy at the moment).

We'll start by implementing 1 and 2, while the 3rd would change the exposed API and impose additional requirements on the user of the library, hence why we de-prioritize that.

**Comment by cdecker** [comment]
Should be fixed by #195 :-)

**Comment by cdecker** [comment]
Closing as fixed by #195, but feel free to reopen if this re-appears :-)

**Comment by Jasonvdb** [comment]
I'm still getting this occasionally using the breez sdk swift bindings. Seems to resolve itself eventually. Is it just a matter of waiting for the node to be upgraded?
[backtrace.txt](https://github.com/Blockstream/greenlight/files/12039974/backtrace.txt)

**Comment by Jasonvdb** [comment]
Ah apologies I missed that update, was still using 0.1.1. Thanks!
